"de": {
  "layout-label": "Layout",

  "item-card-label": "Kategorietext",
  "item-card-text": "Textanzeige und Reihenfolge",
  "item-card-tooltip": "Du kannst die Beschreibungen der Kategorien in der PlentyONE Backend-UI unter Artikel » Kategorie verwalten.",
  "category-placeholder": "Kategoriename",
  "category-name": "Kategoriename",
  "category-description-1": "Kategoriebeschreibung 1",
  "category-description-2": "Kategoriebeschreibung 2",
  "short-description": "Kurzbeschreibung",
  "drag-reorder-aria": "Ziehen zum Sortieren",
  "show-subcategories-label": "Direkte Unterkategorien anzeigen",
  "show-subcategories-yes": "Ja",
  "show-subcategories-no": "Nein",
  "subcategories-source-label": "Quelle der Unterkategorien",
  "source-default": "Standard",
  "source-manual": "Manuell",
  "subcategory-item-label": "Unterkategorie",
  "show-brands-label": "Marken anzeigen",
  "brands-source-label": "Markenquelle",
  "brand-item-label": "Marke",
  "link-name-placeholder": "Name",
  "link-url-placeholder": "Link",
  "add-subcategory-link-label": "Unterkategorie hinzufügen",
  "add-brand-link-label": "Marke hinzufügen",
  "remove-link-label": "Entfernen",
  "padding-label": "Innenabstand",

  "image-label": "Bild",
  "display-category-image-label": "Kategoriebild anzeigen",
  "off": "Aus",
  "image-1": "Bild 1",
  "image-2": "Bild 2",

  "image-scalling-label": "Bildskalierung",
  "image-scalling-tooltip": "Einpassen: Das Bild behält sein ursprüngliches Seitenverhältnis bei und wird in den verfügbaren Bereich eingepasst, sodass Innenabstände möglich sind. Füllen: Das Bild füllt den verfügbaren Bereich vollständig aus, wobei Teile des Bildes abgeschnitten werden können und Innenabstände ignoriert werden.",
  "image-scalling-fit-label": "Einpassen",
  "image-scalling-fill-label": "Füllen",

  "image-brightness-label": "Helligkeit",
  "image-alt-label": "Alt-Text",
  "image-alt-hint": "Alternativer Bildtext",

  "pretitle-label": "Vortitel",
  "pretitle-placeholder": "Vortitel",
  "main-title-label": "Haupttitel",
  "main-title-placeholder": "Titel",
  "subtitle-label": "Untertitel",
  "subtitle-placeholder": "Untertitel",
  "description-label": "Beschreibung",
  "description-placeholder": "Text, der HTML-Formatierung unterstützt",

  "text-color-label": "Textfarbe",
  "textbox-background-label": "Textbox-Hintergrund",
  "textbox-color-label": "Textbox-Farbe",
  "textbox-opacity-label": "Textbox-Deckkraft",

  "textbox-align-x-label": "Textbox-Ausrichtung (x)",
  "textbox-align-x-left-label": "Links",
  "textbox-align-x-center-label": "Zentriert",
  "textbox-align-x-right-label": "Rechts",

  "textbox-align-y-label": "Textbox-Ausrichtung (y)",
  "textbox-align-y-top-label": "Oben",
  "textbox-align-y-center-label": "Zentriert",
  "textbox-align-y-bottom-label": "Unten",

  "text-align-label": "Textausrichtung (x)",
  "text-align-option-left-label": "Links",
  "text-align-option-center-label": "Zentriert",
  "text-align-option-right-label": "Rechts",

  "field-empty-hint-prefix": "Das Feld {field} enthält keinen Inhalt",
  "fields-empty-hint-prefix": "Die Felder {fields} enthalten keinen Inhalt",
  "image-slot-empty-hint-prefix": "Der ausgewählte Bild-Slot hat kein verknüpftes Bild",
  "learn-more": "Mehr erfahren"
}